language: python
cache: pip
python:
- '3.6'
- '3.8'
install: pip3 install build
script: python3 -m build --wheel
notifications:
  email:
    on_failure: always
    on_pull_requests: always
deploy:
  provider: pypi
  username: Zapunidi
  password:
    secure: JsFD1DlWZaPDyoWjg+X+hFvBoqyFqg61tUVSfGCdZHvJKF+wSsNvttcaZcRnoJR2HXPquVYxdOVllZmM/DZ1vp/rziqlyTW5GCOSnN4cINi0OlKxazwvMgfapx1AE1Y/hqtRkcXXwA8A/lRd39TPm5KFrtFfq1VbPqaH/U2+DvLFU7JUCDZzvGb7zbhydXREhMkjYZBRJxUYW6g1ddYOZfnIEtoWzhB931PwzSKfDcTGdUYzn7QR6GDoLkhWr76+5xudj7INQTGkFUR/Rwbw8dF4DNSRCf0l0fhTUQg6/hxX6VbL08D3t+913sLbBJkWEnhPRJXj18iAEVx1dsQS0b4gxuxc6X+6+PG8k+c0r4yENJ51BpLHLt0dhb/h8sWoW61DN9qZIeF/N6b06Z00gRsAH2yYpA5UKzGW075+/26xY3FcF/Pd+hFP5TKJfO03pEBfQtKX3FYo+D9du4RTC1pnx0zJq39yBSPPnWZhgz6SLN0qaoR2crAXrOOjqcmbNbz2o6nRyZ5zGndvPpPbueDDN6qDkS+KFHqVq4Zk9hRI7/KymG5G63DD1elvLZvtNIXN8uy+8nBzM3K/nEUbBA6jPfP77TseTzSlTR4RiKsJDyFMDSl/gLdfRXazhE1wGkAv9yHDXHprWzkhy3+6pw2Ss/Bty6z0MGkNarSJbr8=
  on:
    tags: true
